project:
  type: website
  output-dir: docs

website:
  title: "Raghul Senthil Selvan Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: LinkdIn
        href: https://www.linkedin.com/in/raghuls/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

